# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210104_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
